name: Auto Tag, Release, and Build

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC build cache
        uses: actions/cache@v4
        with:
          path: |
            x64/Release
          key: ${{ runner.os }}-msvc-${{ hashFiles('**/*.cpp', '**/*.h', '**/*.vcxproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-msvc-

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build DLL (Release, x64)
        run: msbuild CarbonInjector.sln /p:Configuration=Release /p:Platform=x64

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Create tag
        id: tag
        run: |
          $TAG_NAME = "ci-${{ steps.vars.outputs.sha_short }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag_name=$TAG_NAME" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          body: "Automated release for commit ${{ steps.vars.outputs.sha_short }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List x64/Release directory contents
        run: |
          echo Listing x64/Release directory:
          dir x64\Release
        shell: cmd

      - name: List workspace directory contents
        run: |
          echo Listing workspace root directory:
          dir
        shell: cmd

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: CarbonInjector-Release-x64
          path: |
            x64/Release/CarbonInjector.dll
            x64/Release/*.pdb
